# Allow anyone who has been /op'ed to bypass all permission checks
# (effectively making them have the same control as console)
ops-bypass-permissions: true

# The translation file you wish to use. (Default: messages.en_us.yml)
translation-file: "messages.en_us.yml"

enable-medallions: false

allow-selling: true

# Amount of time before being put into AFK mode (in seconds)
afk-timeout: 300

# Print debug statements to the console
debug: false

#The name of the server StickyCommands is running on
server: "lobby"

database:
  host: 127.0.0.1
  port: 5432
  database-name: stickycommands
  username: stickycommands
  password: stixil
  table-prefix: stickycommands_
  # Maximum number of times sql will try to reconnect
  max-reconnects: 5
  # Use SSL?
  use-ssl: allow