name: StickyCommands
version: 3.3.1
main: com.dumbdogdiner.stickycommands.StickyCommands
load: STARTUP
authors:
- NotZachery
- aakatz3/Rodwuff
softdepend:
- PlaceholderAPI
- Vault
- LuckPerms
- StaffFacilities
api-version: 1.16
