name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        version: ["11", "14", "15", "16"]
    container:
      image: jcxldn/openjdk-alpine:${{matrix.version}}-jdk
    steps:
    - uses: actions/checkout@v2
    - name: Install maven
      run: apk add --no-cache maven git
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Install dependencies for coverage reporter (java 11 only)
      run: apk add -U --no-cache bash curl ca-certificates
      if: matrix.version == '11'
    - name: Upload code coverage (java 11 only)
      uses: codecov/codecov-action@v1
      if: matrix.version == '11'
    - name: Save build artifact
      uses: actions/upload-artifact@v2
      with:
        name: java-${{matrix.version}}
        path: build/libs/*
  license-header-check:
    runs-on: ubuntu-latest
    container:
      image: jcxldn/openjdk-alpine:11-jdk
    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run the license formatter checker
      run: ./gradlew licenseMain licenseTest
